### ISSUE TITLE
Serial number reading

### ISSUE THREAD

**Issue by skitsanos** [fregmented/SGP30_ESP-IDF#1]
Hi, i can see you are reading 9 bytes for serial number on https://github.com/seyriz/SGP30_ESP-IDF/blob/d568739fa6eee3e35f3160ff1d85016e65661171/components/SGP30/SGP30.c#L158

Docs state it is 48bit number, so shouldn't be there 6 bytes?

**Comment by fregmented** [comment]
SGP30's data frame is constructed with CRC.
Each 2byte of data and 1byte of CRC.
It is reason for read 9bytes.
